default: &default
  adapter: postgresql
  database: mobile2you
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
 
test:
  <<: *default
 
production:
  <<: *default
 